package engine;

import baseServe.comandoEvent;
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author zequi
 */
public class Jogo extends javax.swing.JPanel {

     public String room;
     public int index;
    /**
     * Creates new form Jogo
     */
    public Jogo(String room,int index) { 
        System.out.println("index: "+index);
        initComponents();
        this.room=room;
        this.index=index;
        panelVencedor.setVisible(false);
        jLabel6.setVisible(false);
        jLabel2.setVisible(false);
        View.Tela = "Jogo";
        //player1.setText("Player: "+View.nickName);
        load();
    }

    
    private void load(){
    // 
    
     setButtonsVisivel(false);
         View.clinte.events.put("playersRoom", new comandoEvent() {
                @Override
                public void event(String value) {
                   if("Jogo".equals(View.Tela)){
                       
                       String[] playes = value.split(",");
                        player1.setText("Player: "+playes[0]);
                        player2.setText("Player: "+playes[1]);
                 
           
                }}
                
            });
             View.clinte.events.put("newPartida", new comandoEvent() {
                @Override
                public void event(String value) {
                   if("Jogo".equals(View.Tela)){
                       
                       if(View.nickName == null ? value == null : View.nickName.equals(value)){
                       setButtonsVisivel(true);
                       }
                 
           
                }}
                
            });
             
            View.clinte.events.put("newJogada", new comandoEvent() {
                @Override
                public void event(String value) {
                   if("Jogo".equals(View.Tela)){
                       String[] values = value.split(",");
                       System.out.println("values: "+value);
                       jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/"+values[0]+".png")));
                       jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/"+values[1]+".png")));
           
                }}
                
            });
             
             
            
    
    }
    
    
    
    public void setButtonsVisivel(boolean v){
   
        BPedra.setEnabled(v);
        BPapel.setEnabled(v);
        BTesoura.setEnabled(v);
        BPedra.setBackground( v == false ? Color.GRAY : ((ButtonController)BPedra).corPrimaria);
        BPapel.setBackground( v == false ? Color.GRAY : ((ButtonController)BPapel).corPrimaria);
        BTesoura.setBackground( v == false ? Color.GRAY : ((ButtonController)BTesoura).corPrimaria);
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVencedor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        player1 = new javax.swing.JLabel();
        player2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BPapel = new ButtonController(255, 255, 153);
        BTesoura = new ButtonController(102, 204, 255);
        BPedra = new ButtonController(255, 0, 51);

        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setLayout(null);

        panelVencedor.setBackground(new Color(208,223,255)
        );

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/interrogacao.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/papel.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/vs.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vencedor");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Vencedor");

        javax.swing.GroupLayout panelVencedorLayout = new javax.swing.GroupLayout(panelVencedor);
        panelVencedor.setLayout(panelVencedorLayout);
        panelVencedorLayout.setHorizontalGroup(
            panelVencedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVencedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVencedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelVencedorLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelVencedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelVencedorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelVencedorLayout.setVerticalGroup(
            panelVencedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVencedorLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(panelVencedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(panelVencedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVencedorLayout.createSequentialGroup()
                    .addContainerGap(290, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(99, 99, 99)))
        );

        add(panelVencedor);
        panelVencedor.setBounds(0, 70, 500, 430);

        player1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        player1.setText("Player:");
        add(player1);
        player1.setBounds(10, 0, 270, 40);

        player2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        player2.setText("Player: ?");
        add(player2);
        player2.setBounds(10, 40, 450, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/oie_transparent.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 20, 500, 480);

        BPapel.setBackground(new java.awt.Color(255, 255, 153));
        BPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engine/pedra.png"))); // NOI18N
        BPapel.setBorder(null);
        BPapel.setBorderPainted(false);
        BPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPapelActionPerformed(evt);
            }
        });
        add(BPapel);
        BPapel.setBounds(60, 250, 180, 170);

        BTesoura.setBackground(new java.awt.Color(102, 204, 255));
        BTesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engine/pedra.png"))); // NOI18N
        BTesoura.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTesoura.setBorderPainted(false);
        BTesoura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTesouraActionPerformed(evt);
            }
        });
        add(BTesoura);
        BTesoura.setBounds(270, 250, 160, 170);

        BPedra.setBackground(new java.awt.Color(255, 0, 51));
        BPedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engine/pedra.png"))); // NOI18N
        BPedra.setBorder(null);
        BPedra.setBorderPainted(false);
        BPedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPedraActionPerformed(evt);
            }
        });
        add(BPedra);
        BPedra.setBounds(160, 80, 180, 170);
    }// </editor-fold>//GEN-END:initComponents

    private void BTesouraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTesouraActionPerformed
         if(BTesoura.isEnabled()){jogada("tesoura");}
    }//GEN-LAST:event_BTesouraActionPerformed

    private void BPedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPedraActionPerformed
         if(BPedra.isEnabled()){jogada("pedra");}
    }//GEN-LAST:event_BPedraActionPerformed

    private void BPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPapelActionPerformed
        if(BPapel.isEnabled()){jogada("papel");}
    }//GEN-LAST:event_BPapelActionPerformed


    public void jogada(String jogada){
    
   
      View.clinte.send("roomJogada", index+","+View.nickName+","+jogada);
              
      panelVencedor.setVisible(true);
    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BPapel;
    private javax.swing.JButton BPedra;
    private javax.swing.JButton BTesoura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelVencedor;
    private javax.swing.JLabel player1;
    private javax.swing.JLabel player2;
    // End of variables declaration//GEN-END:variables
}
